obs space:
  name: insitu_surface_altkob
  obsdatain:
    engine:
      type: H5File
      obsfile: ${DATA}/obs/${OPREFIX}insitu_surface_altkob.${PDY}${cyc}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: ${DATA}/diags/insitu_surface_altkob.${PDY}${cyc}.nc4
  simulated variables: [seaSurfaceTemperature]
  io pool:
    max pool size: 1
obs operator:
  name: Identity
  observation alias file: obsop_name_map.yaml
obs error:
  covariance model: diagonal
obs filters:
- filter: Perform Action
  action:
    name: assign error
    error function:
      name: ObsFunction/LinearCombination
      options:
        variables:
        - ObsError/seaSurfaceTemperature
        coefs:
        - 1000.0
obs localizations:
- localization method: Rossby
  base value: 100.0e3
  rossby mult: 1.0
  min grid mult: 2.0
  min value: 200.0e3
  max value: 900.0e3
