obs space:
  name: insitu_profile_glider
  obsdatain:
    engine:
      type: H5File
      obsfile: ${DATA}/obs/${OPREFIX}insitu_profile_glider.${PDY}${cyc}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: ${DATA}/diags/insitu_profile_glider.${PDY}${cyc}.nc4
  simulated variables: [waterTemperature]
  observed variables: [waterTemperature]
  io pool:
    max pool size: 1
obs operator:
  name: Composite
  components:
  - name: InsituTemperature
    variables:
    - name: waterTemperature
obs error:
  covariance model: diagonal
obs filters:
- filter: Perform Action
  action:
    name: assign error
    error function:
      name: ObsFunction/LinearCombination
      options:
        variables:
        - ObsError/waterTemperature
        coefs:
        - 1000.0

obs localizations:
- localization method: Rossby
  base value: 100.0e3
  rossby mult: 1.0
  min grid mult: 2.0
  min value: 200.0e3
  max value: 900.0e3
